wireless_plugs:
    -
        id: 1
        name: 'Plug A'
        house_code: '10000'
        switch_code: '10000'
        state: OFF
    -
        id: 2
        name: 'Plug B'
        house_code: '10000'
        switch_code: '01000'
        state: OFF
    -
        id: 3
        name: 'Plug C'
        house_code: '10000'
        switch_code: '00100'
        state: OFF
    -
        id: 4
        name: 'Plug D'
        house_code: '10000'
        switch_code: '00010'
        state: OFF
    -
        name: 'Awesome Plug'
        house_code: '11111'
        switch_code: '11111'
        state: ON
        id: 5
